<?php $this->headTitle()->prepend($this->translate('My Spotify Profile')); ?>

<?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', '/spotify/save');
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
?>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <h2><i class="fa fa-spotify"></i> Spotify Sync <small><?php echo $this->translate('Setup your Spotify profile')?></small></h2>
                <hr/>
                <p><?php echo $this->translate('Here you can set the Spotify profile to share your preferite music playlist in this website. When you set your spotify here, the photos will be published in your website profile.')?></p>
    
                <?php echo $this->formLabel($form->get('playlists')); ?>
                <?php echo $this->formElement($form->get('playlists')); ?>
                <?php echo $this->formElementErrors($form->get('playlists')); ?>
            </div>
            <div class="text-right">
                <?php echo $this->formElement($form->get('submit')); ?>
        	</div>
        </div>
    </div>
</div>

<?php echo $this->form()->closeTag() ?>
